### ISSUE TITLE
Please provide copyright licensing terms for the source code

### ISSUE THREAD

**Issue by petterreinholdtsen** [Matthias-Wandel/lathe-thread-gears#2]
At the moment there is no statement about the licensing terms of this collection of source code.  Please state the terms and add a copyright declaration at the top of `lathe_thread_gears.py`.

May I propose to use the GPLv2+ license?  You could do so by adding this to the top of `lathe_thread_gears.py` and including a COPYING file with the full license.  Let me know if you want me to create a pull request doing this.

```
# Copyright (C) 2024 Matthias Wandel
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2, or (at your option) any
# later version.
#
# This file is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
```

**Comment by Matthias-Wandel** [comment]
its a 200 line python script.  Do whatever you want with it.

**Comment by Matthias-Wandel** [comment]
Is a 200 line python script.  Don't need a huge license for that, do whatever you want.
And if that's a problem, then don't use it.

**Comment by petterreinholdtsen** [comment]
[Matthias Wandel]
> Is a 200 line python script.  Don't need a huge license for that, do
> whatever you want.

I agree that there is no need for a huge license.

Sadly the copyright law applies automatically on all works.  If sound
like you want it to be except from copyright law.  If so, I suggest to
slap a <URL: https://wiki.creativecommons.org/wiki/Public_domain >
sticker on it instead, and mark it as Creative Commonz Zero,
<URL: https://creativecommons.org/publicdomain/zero/1.0/>.  Something
like this at the top of the file might work:

# To the extent possible under law, the author(s) have dedicated all
# copyright and related and neighboring rights to this software to the
# public domain worldwide. This software is distributed without any
# warranty.
# The terms of this lisense is available from
# https://creativecommons.org/publicdomain/zero/1.0/.

> And if that's a problem, then don't use it.

As the Copyright law prohibits use unless otherwise granted with a
license, it is not legally usable without it.  It would be nice to
legally be able to copy, share and use the git content.

-- 
Happy hacking
Petter Reinholdtsen
